name: Release

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    tags:
      - 'v*'

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  release:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["linux"]
        arch: ["386", "amd64", "arm-7", "arm64", "riscv64"]
    env:
      GO_VERSION: 1.22.4 # TODO perhaps just have a "SERVER_VERSION" file in repo?
      PLUGIN_NAME: gotify-slack-webhook
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build in Container
        run: |
          docker run -v ${{ github.workspace }}:/build \
          gotify/build:${{ env.GO_VERSION }}-${{ matrix.os }}-${{ matrix.arch }} \
          go build -a -installsuffix cgo -ldflags "-w -s" -buildmode=plugin -o /build/out/${{ env.PLUGIN_NAME }}-${{ matrix.arch }}.so /build
      - name: "Archive build artifacts"
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: build-output
          path: build/out/*.so
