name: Release

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    tags:
      - 'v*'

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  build:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["linux"]
        arch: ["386", "amd64", "arm-7", "arm64"]
    env:
      GO_VERSION: 1.22.4 # TODO perhaps just have a "SERVER_VERSION" file in repo?
      OUT_FILE: gotify-slack-webhook-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build in Container
        run: |
          docker run -v ${{ github.workspace }}:/build -w /build \
          gotify/build:${{ env.GO_VERSION }}-${{ matrix.os }}-${{ matrix.arch }} \
          go build -a -installsuffix cgo -ldflags "-w -s" -buildmode=plugin -o out/${{ env.OUT_FILE }}.so
      - name: "Archive build artifacts"
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: ${{ env.OUT_FILE }}
          path: out/${{ env.OUT_FILE }}.so

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          artifacts: "gotify-slack-webhook*/*.so"
          generateReleaseNotes: true

  bundle-container:
    needs: build
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: lukasknuth/gotify-slack-webhook-bundled
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      - name: Move build output into shared folder
        run: |
          ls -R
          mkdir out
          mv gotify-slack-webhook*/*.so out/
      - name: Rename ARMv7 plugin so Docker finds it
        # NOTE: `docker buildx` differentiates by Arch only (amd64/arm64/arm), not variant (v7)
        run: mv out/gotify-slack-webhook-arm-7.so out/gotify-slack-webhook-arm.so
      - uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - name: Generate Container Metadata from git
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: meta
        with:
          images: ${{ env.IMAGE_NAME }}
      - uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@4f7cdeb0f05278b464e71357394bf2c61f94138e # v6.6.0
        with:
          context: .
          file: bundle.Dockerfile
          push: true
          # NOTE: 386 missing because there is no official image.
          platform: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
