name: Release

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    tags:
      - 'v*'

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  build:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["linux"]
        arch: ["386", "amd64", "arm-7", "arm64"]
    env:
      GO_VERSION: 1.22.4 # TODO perhaps just have a "SERVER_VERSION" file in repo?
      OUT_FILE: gotify-slack-webhook-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build in Container
        run: |
          docker run -v ${{ github.workspace }}:/build -w /build \
          gotify/build:${{ env.GO_VERSION }}-${{ matrix.os }}-${{ matrix.arch }} \
          go build -a -installsuffix cgo -ldflags "-w -s" -buildmode=plugin -o out/${{ env.OUT_FILE }}.so
      - name: "Archive build artifacts"
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: ${{ env.OUT_FILE }}
          path: out/${{ env.OUT_FILE }}.so

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        with:
          artifacts: "gotify-slack-webhook*"
          generateReleaseNotes: true
